# Generated by Django 4.2.20 on 2025-12-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "course_key",
                    opaque_keys.edx.django.models.CourseKeyField(
                        db_index=True, max_length=255
                    ),
                ),
                ("block_id", models.CharField(max_length=1024)),
                ("rating", models.IntegerField(default=0, verbose_name="Rating")),
                (
                    "block_name",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="User Feedback"
                    ),
                ),
                (
                    "consent_to_share",
                    models.BooleanField(
                        default=True,
                        help_text="Check this box to consent to your feedback being shared publicly by the EBC Learning on its website, social media, and promotional materials.",
                        verbose_name="Consent to Share Feedback",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to approve this feedback for public display on the course page.",
                        verbose_name="Approved for Display",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_submitted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Course Feedback",
            },
        ),
        migrations.CreateModel(
            name="ShareFeedbackWith",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "course_key",
                    opaque_keys.edx.django.models.CourseKeyField(
                        db_index=True,
                        help_text="The course key of the course version with which the feedback is shared.",
                        max_length=255,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Feedback Course",
                "verbose_name_plural": "Shared Feedback Courses",
                "db_table": "feedback_shared_courses",
                "indexes": [
                    models.Index(
                        fields=["course_key"], name="feedback_sh_course__b397d3_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sharefeedbackwith",
            constraint=models.UniqueConstraint(
                fields=("feedback", "course_key"), name="unique_feedback_course_key"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["course_key", "is_approved", "consent_to_share"],
                name="feedback_fe_course__b22f35_idx",
            ),
        ),
    ]
