# Generated by Django 3.2.13 on 2025-01-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="consent_to_share",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to consent to your feedback being shared publicly by the EBC Learning on its website, social media, and promotional materials.",
                verbose_name="Consent to Share Feedback",
            ),
        ),
    ]
