# Generated by Django 3.2.13 on 2025-06-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_consent_to_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to approve this feedback for public display on the course page.",
                verbose_name="Approved for Display",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="consent_to_share",
            field=models.BooleanField(
                default=True,
                help_text="Check this box to consent to your feedback being shared publicly by the EBC Learning on its website, social media, and promotional materials.",
                verbose_name="Consent to Share Feedback",
            ),
        ),
    ]
