# Generated by Django 3.2.13 on 2025-06-27 02:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_auto_20250624_2233"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareFeedbackWith",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "course_key",
                    opaque_keys.edx.django.models.CourseKeyField(
                        db_index=True,
                        help_text="The course key of the course version with which the feedback is shared.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Feedback Course",
                "verbose_name_plural": "Shared Feedback Courses",
                "db_table": "feedback_shared_courses",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Course Feedback",
            },
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["course_key", "is_approved", "consent_to_share"],
                name="feedback_fe_course__b22f35_idx",
            ),
        ),
        migrations.AddField(
            model_name="sharefeedbackwith",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedback.feedback"
            ),
        ),
        migrations.AddIndex(
            model_name="sharefeedbackwith",
            index=models.Index(
                fields=["course_key"], name="feedback_sh_course__b397d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharefeedbackwith",
            constraint=models.UniqueConstraint(
                fields=("feedback", "course_key"), name="unique_feedback_course_key"
            ),
        ),
    ]
